#!/bin/bash
# ■ここから拡張

# 日本語パック
code --install-extension MS-CEINTL.vscode-language-pack-ja --force

# コーディング支援
code --install-extension visualstudioexptteam.vscodeintellicode --force

# markdown
code --install-extension yzane.markdown-pdf --force
code --install-extension davidanson.vscode-markdownlint --force
code --install-extension alanwalk.markdown-toc --force
code --install-extension legendmohe.markdown-index --force
code --install-extension mushan.vscode-paste-image --force

code --install-extension esbenp.prettier-vscode --force

code --install-extension donjayamanne.githistory --force

code --install-extension alefragnani.bookmarks --force

code --install-extension jebbs.plantuml --force

code --install-extension christian-kohler.path-intellisense --force

code --install-extension codezombiech.gitignore --force
code --install-extension fabiospampinato.vscode-todo-plus --force
code --install-extension ibm.output-colorizer --force
code --install-extension ms-vscode-remote.remote-containers --force
code --install-extension ms-azuretools.vscode-docker --force
